server:
  port: 8090
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 200
        max-idle: 10
        min-idle: 0
    timeout: 1000
  datasource:
    name: dataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/owner?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=UTC
    username: root
    password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  data:
    mongodb:
      database: des_romm_db
      uri: mongodb://localhost:27017/des_romn_db
mybatis:
  mapper-locations: classpath:mybatis/mapper/user/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
#----------------swagger配置-----------------------
swagger:
  enable: false
#--------------------极光推送配置------------------------------
jpush:
  appKey: 857d8aa9313a2ce76c29d27f
  masterSecret: b551792c19cf170ad075965e
#
#secure:
#  ignored:
#    urls: "",""